### ISSUE TITLE
rcmd failing because of description version

### ISSUE THREAD

**Issue by smouksassi** [benjaminrich/ttt#1]
Hi Ben hope all good on your end I am a big fan of the ttt package seems unable to install with a version
like : 1.1-dev
https://github.com/benjaminrich/ttt/blob/main/DESCRIPTION#L3

can you please change it to something numeric?
1.1.9999

I love ttt thanks for writing this package!

**Comment by benjaminrich** [comment]
Version changed to 1.1.0.
